/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application2;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Label;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author arnavprabhale
 */
public class FeetToInchs extends javax.swing.JFrame
{

    /**
     * Creates new form FeetToInchs
     */
    
    IndexPage ip;
    JButton btnBack, btnconvert;
    FeetToInchs me;
    JLabel lblinputJLabel, lbloutputJLabel, lbloutputnameJLabel;
    TextField txtinputField;
    JTextArea txtoutputField;
    
    

    public FeetToInchs()
    {
        initComponents();
        addImage();
        addComponents();
    }
    
    public FeetToInchs(IndexPage ref)
    {
        ip = ref;
        me = this;
        initComponents();
        addImage();
        addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblmainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Feet to Inches Conversion");
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FeetToInchs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FeetToInchs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FeetToInchs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FeetToInchs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FeetToInchs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblmainLabel;
    // End of variables declaration//GEN-END:variables


private void addImage()
    {
        CommonFunctions.addlabelBackground(lblmainLabel, "/Users/arnavprabhale/NetBeansProjects/RealApplications/src/main/java/images2/board3.jpeg");
    }

    private void addComponents()
    {
        Font f = new Font("arial", Font.BOLD, 21);
        Font newFont = new Font("thonburi", Font.PLAIN, 18);
        Color b = new Color(14, 37, 7);
        
        lblinputJLabel = new JLabel("Feet");
        lblinputJLabel.setForeground(Color.WHITE);
        lblinputJLabel.setFont(newFont);
        lblinputJLabel.setBounds(175, 150, 150, 50);
        lblinputJLabel.setAlignmentY(Label.LEFT);
        lblmainLabel.add(lblinputJLabel);
        
        txtinputField = new TextField();
        txtinputField.setBackground(Color.WHITE);
        txtinputField.setForeground(Color.BLACK);
        txtinputField.setFont(newFont);
        txtinputField.setBounds(175, 200, 150, 50);
        lblmainLabel.add(txtinputField);
        txtinputField.addKeyListener(new KeyAdapter()
        {
            @Override
            public void keyTyped(KeyEvent e)
            {
                CommonFunctions.conversionValidation(e);
            }

        });
        
        lbloutputnameJLabel = new JLabel("Inches");
        lbloutputnameJLabel.setForeground(Color.WHITE);
        lbloutputnameJLabel.setFont(newFont);
        lbloutputnameJLabel.setBounds(425, 150, 150, 50);
        lblmainLabel.add(lbloutputnameJLabel);
        
        txtoutputField = new JTextArea();
        txtoutputField.setBackground(Color.WHITE);
        txtoutputField.setForeground(Color.BLACK);
        txtoutputField.setFont(newFont);
        txtoutputField.setBounds(425, 200, 150, 50);
        lblmainLabel.add(txtoutputField);
        txtoutputField.addKeyListener(new KeyAdapter()
        {
            @Override
            public void keyTyped(KeyEvent e)
            {
                CommonFunctions.noInputValidation(e);
            }

        });
        
        
        btnBack = new JButton("BACK");
        btnBack.setBounds(10, 450, 100, 40);
        btnBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnBack.setBackground(b);
        btnBack.setForeground(Color.WHITE);
        btnBack.setFont(f);
        btnBack.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                me.setVisible(false);
                ip .setVisible(true);
            }
            
        });
        
        lblmainLabel.add(btnBack);
        
        btnconvert = new JButton("CONVERT");
        btnconvert.setBounds(275, 275, 200, 50);
        btnconvert.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnconvert.setBackground(new Color(207, 210, 214));
        btnconvert.setForeground(Color.BLACK);
        btnconvert.setFont(f);
        btnconvert.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                try
                {
                    float x = Float.parseFloat(txtinputField.getText());
                    float ans = (float)(x * 12);
                    txtoutputField.setText(String.valueOf(ans));   
                } 
                catch (NumberFormatException a)
                {
                    JOptionPane.showMessageDialog(btnconvert, "Please enter Valid Input", "ERROR", JOptionPane.ERROR_MESSAGE);         
                    txtinputField.setText("");
                    txtoutputField.setText("");
                }
            }
            
        });
        lblmainLabel.add(btnconvert);
    
    
    }
}
