/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application2;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *Q2.Miss Natasha Romanoff is a very loving class Teacher at a primary school.
 * She saw that her students are facing difficulties in some conversions.
* So she has decided to develope an application 
for some conversion.She has approached you for this development.
* If she likes design and working of app,she will pay you or you will not get anything.
The requirements of Miss Natasha are as follows
The app should perform conversion of

==Distance and Time Conversion==
A)meter to centimeter
B)km to meter
C)feet to inches
D)Miles to meters
E)Hours to minutes

==Currency Conversion.==
A)Dolar to Rupees
B)Pounds to Rupees
C)Rupees to Dollar
D)Rupees to Pounds

You are required here to give any one extra facility in your 
* app which will help Natasha's students.Natasha will like it.
 */


public class firstPage extends javax.swing.JFrame
{

    /**
     * Creates new form firstPage
     */
    
    JButton btnconversion, btnexit;
    JLabel lbltextJLabel;
    firstPage fp;
    
    public firstPage()
    {
        fp = this;
        initComponents();
        CommonFunctions.addlabelBackground(lblfirstPage, "/Users/arnavprabhale/NetBeansProjects/RealApplications/src/main/java/images2/pencil1.jpeg");
    
        Font f = new Font("arial", Font.BOLD, 25);
        btnconversion = new JButton("CONVERSION");
        btnconversion.setBounds(150, 375, 200, 100);
        btnconversion.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnconversion.setBackground(new Color(226, 226, 226));
        btnconversion.setForeground(Color.BLACK);
        btnconversion.setFont(f);
        btnconversion.addActionListener(new ActionListener()
                {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                IndexPage ip = new IndexPage(fp);
                ip.setVisible(true);
                fp.setVisible(false);
            }
                    
                });
        
        lblfirstPage.add(btnconversion);
        
        btnexit = new JButton("EXIT");
        btnexit.setBounds(400, 375, 200, 100);
        btnexit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnexit.setBackground(new Color(226, 226, 226));
        btnexit.setForeground(Color.BLACK);
        btnexit.setFont(f);
        btnexit.addActionListener(new ActionListener()
                {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                int result = JOptionPane.showConfirmDialog(lblfirstPage, "Want To Exit ?", "Are You Sure", JOptionPane.YES_NO_OPTION);
                
                if(JOptionPane.YES_OPTION == result)
                {
                    fp.dispose();
                    System.exit(0);
                }
                else
                {
                    
                }
                
                
                
            }
                    
                });
        
        lblfirstPage.add(btnexit);
        
        lbltextJLabel = new JLabel("CONVERSIONS   MADE   EASY", SwingConstants.CENTER);
        lbltextJLabel.setBounds(100, 0, 550, 100);
        lbltextJLabel.setForeground(Color.BLACK);
        lbltextJLabel.setFont(new Font("al tarikh", Font.CENTER_BASELINE, 26));
        
        lbltextJLabel.setVisible(true);
        
        lblfirstPage.add(lbltextJLabel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblfirstPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblfirstPage, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblfirstPage, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new firstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblfirstPage;
    // End of variables declaration//GEN-END:variables
}
