/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application2;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author arnavprabhale
 */
public class IndexPage extends javax.swing.JFrame
{

    /**
     * Creates new form IndexPage
     */
    
    JButton btnMeterToCm, btnKmToMtr, btnFeetToInch, btnMilesToMeter, btnHourToMinutes, btnDollarToRupees, btnBack;
    firstPage fp;
    IndexPage ip;
    
    public IndexPage()
    {
        initComponents();
        addImage();
        addComponents();
    }
    public IndexPage(firstPage ref)
    {
        fp = ref;
        ip = this;
        initComponents();
        addImage();
        addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CHOOSE  CONVERSION");
        setUndecorated(true);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new IndexPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mainLabel;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    private void addImage()
    {
        
        CommonFunctions.addlabelBackground(mainLabel, "/Users/arnavprabhale/NetBeansProjects/RealApplications/src/main/java/images2/calculations2.jpeg");
    }

    private void addComponents()
    {
        Font f = new Font("arial", Font.BOLD, 21);
        Color b = new Color(14, 37, 7);
        btnMeterToCm = new JButton("METER TO CENTIMETER");
        btnMeterToCm.setBounds(200, 50, 350, 50);
        btnMeterToCm.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnMeterToCm.setBackground(b);
        btnMeterToCm.setForeground(Color.WHITE);
        btnMeterToCm.setFont(f);
        btnMeterToCm.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                MeterToCentimeter subPage = new MeterToCentimeter(ip);
                subPage.setVisible(true);
                ip.setVisible(false);
            }
            
        });
        
        mainLabel.add(btnMeterToCm);
        
        btnKmToMtr = new JButton("KILOMETER TO METER");
        btnKmToMtr.setBounds(200, 120, 350, 50);
        btnKmToMtr.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnKmToMtr.setBackground(b);
        btnKmToMtr.setForeground(Color.WHITE);
        btnKmToMtr.setFont(f);
        btnKmToMtr.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                KilometerToMeter subPage = new KilometerToMeter(ip);
                subPage.setVisible(true);
                ip.setVisible(false);
            }
            
        });
        
        mainLabel.add(btnKmToMtr);
        
        btnFeetToInch = new JButton("FEET TO INCHS");
        btnFeetToInch.setBounds(200, 190, 350, 50);
        btnFeetToInch.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnFeetToInch.setBackground(b);
        btnFeetToInch.setForeground(Color.WHITE);
        btnFeetToInch.setFont(f);
        btnFeetToInch.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                FeetToInchs subPage = new FeetToInchs(ip);
                subPage.setVisible(true);
                ip.setVisible(false);
            }
            
        });
        
        mainLabel.add(btnFeetToInch);


        btnMilesToMeter = new JButton("MILES TO METER");
        btnMilesToMeter.setBounds(200, 260, 350, 50);
        btnMilesToMeter.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnMilesToMeter.setBackground(b);
        btnMilesToMeter.setForeground(Color.WHITE);
        btnMilesToMeter.setFont(f);
        btnMilesToMeter.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                MilesToMeter subPage = new MilesToMeter(ip);
                subPage.setVisible(true);
                ip.setVisible(false);
            }
            
        });
        
        mainLabel.add(btnMilesToMeter);
        
        btnHourToMinutes = new JButton("HOUR TO MINUTES");
        btnHourToMinutes.setBounds(200, 330, 350, 50);
        btnHourToMinutes.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnHourToMinutes.setBackground(b);
        btnHourToMinutes.setForeground(Color.WHITE);
        btnHourToMinutes.setFont(f);
        btnHourToMinutes.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                System.out.println("in hour button click");
                MilesToMeter subPage = new MilesToMeter(ip, "Hour", "Minutes");
                subPage.setVisible(true);
                ip.setVisible(false);
            }
            
        });
        
        mainLabel.add(btnHourToMinutes);
        
        btnDollarToRupees = new JButton("DOLLAR TO RUPEES");
        btnDollarToRupees.setBounds(200, 400, 350, 50);
        btnDollarToRupees.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnDollarToRupees.setBackground(b);
        btnDollarToRupees.setForeground(Color.WHITE);
        btnDollarToRupees.setFont(f);
        btnDollarToRupees.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                System.out.println("in hour button click");
                MilesToMeter subPage = new MilesToMeter(ip, "Dollar $", "Rupees ₹");
                subPage.setVisible(true);
                ip.setVisible(false);
            }
            
        });
        
        mainLabel.add(btnDollarToRupees);
        
        btnBack = new JButton("BACK");
        btnBack.setBounds(10, 450, 100, 40);
        btnBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnBack.setBackground(b);
        btnBack.setForeground(Color.WHITE);
        btnBack.setFont(f);
        btnBack.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                ip.setVisible(false);
                fp .setVisible(true);
            }
            
        });
        
        mainLabel.add(btnBack);
        

        
        
        
    
    }
}
